config/routes.rb
Bracket::Application.routes.draw do
  devise_for :users

  get "pages/home"
  get "pages/info"
  get "pages/contact"
  get "pages/table"

  resources :tags
  resources :teams
  resources :users do
    resources :tournaments
  end

  match '/' => 'pages#ncaa', :as => 'user_root'

  match 'teams/:id/add/:tag_id' => 'teams#add_tag', :as => :add_tag, :via => :post
  match 'users/:id/add/:tag_id' => 'users#add_tag', :as => :add_user_tag, :via => :post
  match 'tournaments/:id/add/:tag_id' => 'tournaments#add_tag', :as => :add_tournament_tag, :via => :post
  match 'teams/:id/remove/:tag_id' => 'teams#remove_tag', :as => :remove_tag, :via => :post
  match 'users/:id/remove/:tag_id' => 'users#remove_tag', :as => :remove_user_tag, :via => :post
  match 'tournaments/:id/remove/:tag_id' => 'tournaments#remove_tag', :as => :remove_tournament_tag, :via => :post
  match 'tournaments/:id/questions' => 'tournaments#questions', :as => :tournament_questions, :via => :get
  match 'tournaments/:id/questions' => 'tournaments#update_questions', :as => :tournament_questions, :via => :post
  match 'tournaments/:id/redo' => 'tournaments#redo', :as => :tournament_redo, :via => :post

  root :to => "pages#ncaa"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  belongs_to :team
  has_many :tournaments
  has_and_belongs_to_many :tags
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
      format.js  { render :layout => false }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = current_user
    @tournaments = @user.tournaments
    @tags = Tag.all
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
      format.js  { render :layout => false }
    end
  end

  # GET /users/1/edit
  def edit
    @user = current_user

    respond_to do |format|
      format.html # new.html.erb
      format.js { render :layout => false }
    end

  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
#    @user = User.find(params[:id])

    current_user.team = Team.find(params[:user][:team_id])
    current_user.team.save!

    respond_to do |format|
      if current_user.update_attributes(params[:user])
        format.html { redirect_to(root_path(), :notice => 'User was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label><b>What is your name?</b></label>
    <%= f.text_field :name %>
  </div>

  <div class="field">
  <label><b>What is your favorite team? </b></label> <%= collection_select(:user, :team_id, Team.all, :id, :name, :prompt => true) %>
  </div></br><br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%#= link_to 'Show', current_user %> 
<%#= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.team.name if user.team %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit Info', edit_user_path(user) %></td>
    <td><%= link_to 'Delete Account', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Team:</b>
  <%= @user.team.name %>
</p>
<h2>Tournaments:</h2>
<% @tournaments.each do |tournament| %>
  <%= tournament.name %>: 
  <%= link_to 'Questions/Tags', tournament_questions_path(tournament) %>  
  <% if tournament.tags.empty? %>
    Create Tags Before you can view...
  <% elsif tournament.games.empty? %>
    <%= link_to "Build", user_tournament_path(@user,tournament) %>
  <% else %>
    <%= link_to "View", user_tournament_path(@user,tournament) %>
  <% end %>
<br/>
<% end %>
<br/><%= link_to 'New Tournament', new_user_tournament_path(@user) %><br/>
<br/>


<%# @user.tags.each do |tag| %>
  <%#= tag.name %> <%#= link_to 'Remove', remove_user_tag_path(@user,tag), :method => :post %><br/>
<%# end %>

<%# @tags.each do |tag| %>
  <%#= link_to tag.name, add_user_tag_path(@user,tag), :method => :post %><br/>
<%# end %>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>