config/routes.rb
Bracket::Application.routes.draw do
  devise_for :users

  get "pages/home"
  get "pages/info"
  get "pages/contact"
  get "pages/table"

  resources :tags
  resources :teams
  resources :users do
    resources :tournaments
  end

  match '/' => 'pages#ncaa', :as => 'user_root'

  match 'teams/:id/add/:tag_id' => 'teams#add_tag', :as => :add_tag, :via => :post
  match 'users/:id/add/:tag_id' => 'users#add_tag', :as => :add_user_tag, :via => :post
  match 'tournaments/:id/add/:tag_id' => 'tournaments#add_tag', :as => :add_tournament_tag, :via => :post
  match 'teams/:id/remove/:tag_id' => 'teams#remove_tag', :as => :remove_tag, :via => :post
  match 'users/:id/remove/:tag_id' => 'users#remove_tag', :as => :remove_user_tag, :via => :post
  match 'tournaments/:id/remove/:tag_id' => 'tournaments#remove_tag', :as => :remove_tournament_tag, :via => :post
  match 'tournaments/:id/questions' => 'tournaments#questions', :as => :tournament_questions, :via => :get
  match 'tournaments/:id/questions' => 'tournaments#update_questions', :as => :tournament_questions, :via => :post
  match 'tournaments/:id/redo' => 'tournaments#redo', :as => :tournament_redo, :via => :post

  root :to => "pages#ncaa"

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  has_many :games
  belongs_to :user
  has_and_belongs_to_many :tags

  def clear
    Participant.destroy self.games.collect{|g|g.participants}
    Game.destroy self.games
  end

  def tag_by_kind(kind)
    if self.tags.empty?
      nil
    else
      self.tags.find_by_kind(kind).id
    end
  end

  def build_games
  ## LOOPS ALL GAMES AND PLAYS THEM...PROLLY NEEDS A BETTER NAME

   (0..66).each do |game_number|

      division = case game_number
        when 0..15 then "East"
        when 16..31 then "Midwest"
        when 32..47 then "South"
        when 48..63 then "West"
        when 64..66 then "Final Four"  #WHAT TO DO HERE...
      end

      division_two = nil

      game = self.games.find_or_create_by_number(game_number)

      if(game.status.nil?)
        if game_number < 64
          game.schedule_game(whos_playing(game_number),division)
        elsif game_number == 64
          game.schedule_game(whos_playing(game_number),"East","South")
        elsif game_number == 65
          game.schedule_game(whos_playing(game_number),"Midwest","West")
        elsif game_number == 66
          game.schedule_game(whos_playing(game_number),self.games.find_by_number(64).winner.team.division,self.games.find_by_number(65).winner.team.division)
        end
      end

      if(game.scheduled?)
        game.play_game
      end
     
    end  ## END GAME NUMBER LOOP
  end

  def whos_playing(game_number)
## MIGHT NEED A BETTER WAY TO DO THIS WHEN WE HAVE 68 GAMES....
## COULD LOOP THORUGH EACH DIVISION...then use the same layout, then at the bottom play out the final four
    whos_playing = case game_number
    #EAST
      when 0 then [16,17]
      when 1 then [1,self.games[0].winner.team.seed] ### NEED TO PLAY THIS FIRST
      when 2 then [2,15]
      when 3 then [3,14]
      when 4 then [4,13]
      when 5 then [5,12]
      when 6 then [6,11]
      when 7 then [7,10]
      when 8 then [8,9]
      when 9 then [self.games[1].winner.team.seed,self.games[8].winner.team.seed]
      when 10 then [self.games[2].winner.team.seed,self.games[7].winner.team.seed]
      when 11 then [self.games[3].winner.team.seed,self.games[6].winner.team.seed]
      when 12 then [self.games[4].winner.team.seed,self.games[5].winner.team.seed]
      when 13 then [self.games[9].winner.team.seed,self.games[12].winner.team.seed]
      when 14 then [self.games[11].winner.team.seed,self.games[10].winner.team.seed]
      when 15 then [self.games[13].winner.team.seed,self.games[14].winner.team.seed]
    #MIDWEST
      when 16 then [16,17]
      when 17 then [1,self.games[16].winner.team.seed]
      when 18 then [2,15]
      when 19 then [3,14]
      when 20 then [4,13]
      when 21 then [5,12]
      when 22 then [6,11]
      when 23 then [7,10]
      when 24 then [8,9]
      when 25 then [self.games[17].winner.team.seed,self.games[24].winner.team.seed]
      when 26 then [self.games[18].winner.team.seed,self.games[23].winner.team.seed]
      when 27 then [self.games[19].winner.team.seed,self.games[22].winner.team.seed]
      when 28 then [self.games[20].winner.team.seed,self.games[21].winner.team.seed]
      when 29 then [self.games[25].winner.team.seed,self.games[28].winner.team.seed]
      when 30 then [self.games[27].winner.team.seed,self.games[26].winner.team.seed]
      when 31 then [self.games[29].winner.team.seed,self.games[30].winner.team.seed]
    #SOUTH
      when 32 then [16,17]
      when 33 then [1,self.games[32].winner.team.seed]
      when 34 then [2,15]
      when 35 then [3,14]
      when 36 then [4,13]
      when 37 then [5,12]
      when 38 then [6,11]
      when 39 then [7,10]
      when 40 then [8,9]
      when 41 then [self.games[33].winner.team.seed,self.games[40].winner.team.seed]
      when 42 then [self.games[34].winner.team.seed,self.games[39].winner.team.seed]
      when 43 then [self.games[35].winner.team.seed,self.games[38].winner.team.seed]
      when 44 then [self.games[36].winner.team.seed,self.games[37].winner.team.seed]
      when 45 then [self.games[41].winner.team.seed,self.games[44].winner.team.seed]
      when 46 then [self.games[43].winner.team.seed,self.games[42].winner.team.seed]
      when 47 then [self.games[45].winner.team.seed,self.games[44].winner.team.seed]
    #WEST
      when 48 then [16,17]
      when 49 then [1,self.games[48].winner.team.seed]
      when 50 then [2,15]
      when 51 then [3,14]
      when 52 then [4,13]
      when 53 then [5,12]
      when 54 then [6,11]
      when 55 then [7,10]
      when 56 then [8,9]
      when 57 then [self.games[49].winner.team.seed,self.games[56].winner.team.seed]
      when 58 then [self.games[50].winner.team.seed,self.games[55].winner.team.seed]
      when 59 then [self.games[51].winner.team.seed,self.games[54].winner.team.seed]
      when 60 then [self.games[52].winner.team.seed,self.games[53].winner.team.seed]
      when 61 then [self.games[57].winner.team.seed,self.games[60].winner.team.seed]
      when 62 then [self.games[59].winner.team.seed,self.games[58].winner.team.seed]
      when 63 then [self.games[61].winner.team.seed,self.games[62].winner.team.seed]

      when 64 then [self.games[15].winner.team.seed,self.games[47].winner.team.seed]
      when 65 then [self.games[31].winner.team.seed,self.games[63].winner.team.seed]
      when 66 then [self.games[64].winner.team.seed,self.games[65].winner.team.seed]

    end
  end

  def play_games    
    self.games.each do |game_number|
      self.games.find_by_number(game_number).play_game
    end
  end

end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_filter :authenticate_user!, :except => [:show]

  # GET /tournaments
  # GET /tournaments.xml
  def index
    @user = User.find(params[:user_id])
    @tournaments = @user.tournaments

    respond_to do |format|
      format.html # index.html.erb
      format.js   { render :layout => false }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.xml
  def show
    @user = User.find(params[:user_id])
    @tournament = Tournament.find(params[:id])
    @tags = Tag.order("kind").all
    if @tournament.games.count < 66
      ##CREATE GAMES
      @tournament.build_games
    end

    @games = @tournament.games

    respond_to do |format|
      format.html # show.html.erb
      format.js   { render :layout => false }
    end
  end

  def redo
    @tournament = Tournament.find(params[:id])

    @tournament.clear

    respond_to do |format|
      format.html { redirect_to(user_tournament_url(@tournament.user,@tournament), :notice => 'Rebuilt!') }
      format.js { render :layout => false }
    end
  end


  def questions
    @tournament = Tournament.find(params[:id])
    @user = @tournament.user
    @tags = Tag.order("kind").all

    respond_to do |format|
      format.html # show.html.erb
      format.js { render :layout => false }
    end
  end

  def update_questions
    @tournament = Tournament.find(params[:id])

#    params[:tag].each do |tag|
#    @tournament.tags.destroy_all
    @tournament.tags.delete_all
    @tournament.tags << Tag.find(params[:tag][:animal])
    @tournament.tags << Tag.find(params[:tag][:state])
    @tournament.tags << Tag.find(params[:tag][:color])
    @tournament.tags << Tag.find(params[:tag][:diety])
    @tournament.tags << Tag.find(params[:tag][:conference])
    @tournament.tags << Tag.find(params[:tag][:person])

    respond_to do |format|
      flash[:notice] = 'Questions successfully updated.'
      format.html { redirect_to(tournament_questions_url(@tournament)) }
      format.js
    end
  end

  def add_tag
    @tournament = Tournament.find(params[:id])
    @tag = Tag.find(params[:tag_id])

    @tournament.tags << @tag
    respond_to do |format|
      flash[:notice] = 'Tag was successfully created.'
      format.html { redirect_to(tournament_questions_url(@tournament)) }
      format.js
    end
  end

  def remove_tag
    @tournament = Tournament.find(params[:id])
    @tag = @tournament.tags.find(params[:tag_id])
    respond_to do |format|
      if @tournament.tags.delete(@tag)
        format.html { redirect_to(tournament_questions_url(@tournament), :notice => 'Tag was successfully deleted.') }
        format.js
      else
        format.html { redirect_to(tournament_questions_url(@tournament), :notice => 'Tag was NOT deleted.') }
        format.js
      end
    end
  end

  # GET /tournaments/new
  # GET /tournaments/new.xml
  def new
    @user = User.find(params[:user_id])
    @tournament = @user.tournaments.new

    respond_to do |format|
      format.html # new.html.erb
      format.js { render :layout => false }
    end
  end

  # GET /tournaments/1/edit
  def edit
    @user = User.find(params[:user_id])
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      format.html # new.html.erb
      format.js { render :layout => false }
    end
  end

  # POST /tournaments
  # POST /tournaments.xml
  def create
    @user = current_user
    @tournament = @user.tournaments.new(params[:tournament])

    respond_to do |format|
      if @tournament.save
        flash[:notice] = "Tournament created!"
        format.html { redirect_to(user_url(@user)) }
        format.js
      else
        flash[:notice] = "Tournament not created!"
        format.html { render :action => "new" }
        format.js
      end
    end
  end

  # PUT /tournaments/1
  # PUT /tournaments/1.xml
  def update
    @user = User.find(params[:user_id])
    @tournament = @user.tournaments.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        flash[:notice] = "Tournament updated!"
        format.html { redirect_to(user_path(@user)) }
        format.js
      else
        flash[:notice] = "Tournament not updated!"
        format.html { render :action => "edit" }
        format.js
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.xml
  def destroy
    @user = User.find(params[:user_id])
    @tournament = @user.tournaments.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to(user_url(@user)) }
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/OLDshow.html.erb
<div class="light">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tournament.name %>
</p>

<p>
  <b>Title:</b>
  <%= @tournament.title %>
</p>
<p>
  <b>User:</b>
  <%= @tournament.user.name unless @tournament.user.nil?%>
</p>
<p>
  <b>Content:</b>
  <%= @tournament.content %>
</p>

<% @games.each do |game| %>
  <% game.teams.each do |team| %>
    <%= team.name %>
  <% end %>
<% end %>
<h2>NOT NEEDED?? Current Tags:</h2>
<%# @tournament.tags.each do |tag| %>
  <%#= tag.name %> <%#= link_to 'Remove', remove_tournament_tag_path(@tournament,tag), :method => :post %><br/>
<%# end %>

<h2>NOT NEEDED?? Possible Tags:</h2>
<%# @tags.each do |tag| %>
  <%#= link_to tag.name, add_tournament_tag_path(@tournament,tag), :method => :post %><br/>
<%# end %>

<% winner = [] %>
<% winner[0] = Team.winner([1,16],@user) %>
<% winner[1] = Team.winner([2,15],@user) %>
<% winner[2] = Team.winner([3,14],@user) %>
<% winner[3] = Team.winner([4,13],@user) %>
<% winner[4] = Team.winner([5,12],@user) %>
<% winner[5] = Team.winner([6,11],@user) %>
<% winner[6] = Team.winner([7,10],@user) %>
<% winner[7] = Team.winner([8,9],@user) %>
<% winner[8] = Team.winner([winner[0],winner[7]],@user) %>
<% winner[9] = Team.winner([winner[1],winner[6]],@user) %>
<% winner[10] = Team.winner([winner[2],winner[5]],@user) %>
<% winner[11] = Team.winner([winner[3],winner[4]],@user) %>
<% winner[12] = Team.winner([winner[8],winner[11]],@user) %>
<% winner[13] = Team.winner([winner[10],winner[9]],@user) %>
<% winner[14] = Team.winner([winner[12],winner[13]],@user) %>


<table>
<tr>
  <td class="bb"><%= Team.find_by_seed(1).n %></td><td></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= Team.find(winner[0]).n %></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(16).n %></td><td class="br"></td><td></td><td></td><td></td>
</tr>
<tr>
  <td></td><td class="br"></td><td class="bb"><%= Team.find(winner[8]).n %></td><td></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(8).n %></td><td class="br"></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= Team.find(winner[7]).n %></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(9).n %></td><td></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class=""></td><td></td><td class="br"></td><td class="bb"><%= Team.find(winner[12]).n %></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(5).n %></td><td></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= Team.find(winner[4]).n %></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(12).n %></td><td class="br"></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td class="br"></td><td class="bb br"><%= Team.find(winner[11]).n %></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(4).n %></td><td class="br"></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= Team.find(winner[3]).n %></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(13).n %></td><td></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class=""></td><td></td><td></td><td class="br"></td><td class="bb"><%= Team.find(winner[14]).n %></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(6).n %></td><td></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%=  Team.find(winner[5]).n %></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(11).n %></td><td class="br"></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td class="br"></td><td class="bb"><%= Team.find(winner[10]).n %></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(3).n %></td><td class="br"></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%=  Team.find(winner[2]).n %></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(14).n %></td><td></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td></td><td class="br"></td><td class="bb br"><%= Team.find(winner[13]).n %></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(7).n %></td><td></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= Team.find(winner[6]).n %></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(10).n %></td><td class="br"></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td></td><td class="br"></td><td class="bb br"><%=  Team.find(winner[9]).n %></td><td></td><td></td>
</tr>
<tr>
  <td class="bb"><%= Team.find_by_seed(2).n %></td><td class="br"></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= Team.find(winner[1]).n %></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= Team.find_by_seed(15).n %></td><td></td><td></td><td></td><td></td>
</tr>
</table>
<%= link_to 'Edit', edit_user_tournament_path(@user,@tournament) %> |
<%= link_to 'Back', user_tournaments_path(@user) %>
</div>

app/views/tournaments/add_tag.js.erb
$("#popup").load("<%= tournament_questions_path(@tournament, :format => 'js') %>");

app/views/tournaments/blank.html.erb
<div class="light">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tournament.name %>
</p>

<p>
  <b>Title:</b>
  <%= @tournament.title %>
</p>
<p>
  <b>User:</b>
  <%= @tournament.user.name unless @tournament.user.nil?%>
</p>
<p>
  <b>Content:</b>
  <%= @tournament.content %>
</p>

<p>
  <b>My Team:</b>
  <%= @tournament.user.team.name + " " + @tournament.user.team.mascot unless @tournament.user.nil?%>
</p>

<h2>Tags Used:</h2>
<% @tournament.tags.each do |tag| %>
  <%= tag.name %> <br/>
<% end %>
<br/>

<%= link_to 'Redo!', tournament_redo_url(@tournament), :method => 'post' %>

<table>
<tr>
  <td class="bb"><%= @tournament.games[0].teams[0].n %></td><td></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= @tournament.games[0].info %></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[0].teams[1].n %></td><td class="br"></td><td></td><td></td><td></td>
</tr>
<tr>
  <td></td><td class="br"></td><td class="bb"><%= @tournament.games[8].info %></td><td></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[7].teams[0].n %></td><td class="br"></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= @tournament.games[7].info %></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[7].teams[1].n %></td><td></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class=""></td><td></td><td class="br"></td><td class="bb"><%= @tournament.games[12].info %></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[4].teams[0].n %></td><td></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= @tournament.games[4].info %></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[4].teams[1].n %></td><td class="br"></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td class="br"></td><td class="bb br"><%= @tournament.games[11].info %></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[3].teams[0].n %></td><td class="br"></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= @tournament.games[3].info %></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[3].teams[1].n %></td><td></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class=""></td><td></td><td></td><td class="br"></td><td class="bb"><%= @tournament.games[14].info %></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[5].teams[0].n %></td><td></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= @tournament.games[5].info %></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[5].teams[1].n %></td><td class="br"></td><td></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td class="br"></td><td class="bb"><%= @tournament.games[10].info %></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[2].teams[0].n %></td><td class="br"></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= @tournament.games[2].info %></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[2].teams[1].n %></td><td></td><td class="br"></td><td class="br"></td><td></td>
</tr>
<tr>
  <td ></td><td></td><td class="br"></td><td class="bb br"><%= @tournament.games[13].info %></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[6].teams[0].n%></td><td></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb"><%= @tournament.games[6].info %></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[6].teams[1].n %></td><td class="br"></td><td class="br"></td><td></td><td></td>
</tr>
<tr>
  <td></td><td class="br"></td><td class="bb br"><%= @tournament.games[9].info %></td><td></td><td></td>
</tr>
<tr>
  <td class="bb"><%= @tournament.games[1].teams[0].n %></td><td class="br"></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="br"></td><td class="bb br"><%= @tournament.games[1].info %></td><td></td><td></td><td></td>
</tr>
<tr>
  <td class="bb br"><%= @tournament.games[1].teams[1].n %></td><td></td><td></td><td></td><td></td>
</tr>
</table>
<%= link_to 'Edit', edit_user_tournament_path(@user,@tournament) %> |
<%= link_to 'Back', user_tournaments_path(@user) %>
</div>

app/views/tournaments/create.js.erb
$("#popup > .popup-header > div.title").html("Questions");
$("#popup > p.body").load("<%= tournament_questions_path(@tournament, :format => 'js') %>");

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', user_tournament_path(@user,@tournament) %> |
<%= link_to 'Back', user_tournaments_path(@user) %>

app/views/tournaments/index.html.erb
<h1>Listing tournaments for <%= @user.name %></h1>

<p id="notice"><%= notice %></p>

<p>
  <label><b>Favorite Team:</b></label>
  <%= @user.team.name if @user.team %>
</p>
<h2>Tournaments:</h2>
<table>
<% @tournaments.each_with_index do |tournament,index| %>
<tr><td>  <%= index + 1 %>. <b><%= tournament.name %>:</b></td>
<td> <%= link_to 'Questions', tournament_questions_url(tournament), :class => "ajax" %></td>
<td>  <% if tournament.tags.empty? %>
    <-- Fill out questions to build your bracket!
  <% elsif tournament.games.empty? %>
    <%= link_to "Build", user_tournament_url(@user,tournament), :class => "ajax-close" %>
  <% else %>
    <%= link_to "View", user_tournament_url(@user,tournament), :class => "ajax-close" %>
  <% end %>
</td>
</tr>
<% end %>
</table>
<br/>
<% if @user.name.nil? %>
<%= link_to 'Edit User Info First!', edit_user_url(@user), :class => "ajax" %>
<% else %>
<%= link_to 'New Tournament', new_user_tournament_url(@user), :class => "ajax" %>
<% end %>
<br/>
<br/>

<%#= link_to 'Edit My Info', edit_user_url(@user), :class => "ajax" %>

app/views/tournaments/questions.html.erb
<h3>Build your bracket by answering a filling out this profile.</h3><br/>

<div class="questions">

<form id="questions-form" class="edit-questions" method="post" action="<%= tournament_questions_path(@tournament) %>" data-remote="true" >
<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>" />
Hi my name is <%= @user.name %>.  
My favorite team is the <%= @user.team.name + " " + @user.team.mascot %>.
The best state in the US is <%= select(:tag, :state, Tag.find_all_by_kind("State").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("State")) %>. 
I think a 
<%= select(:tag, :animal, Tag.find_all_by_kind("Animal").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("Animal")) %> would win in a fight of all animals!
My favorite color is <%= select(:tag, :color, Tag.find_all_by_kind("Color").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("Color")) %>.
The best basketball conference in America is the <%= select(:tag, :conference, Tag.find_all_by_kind("Conference").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("Conference")) %>.
I believe in <%= select(:tag, :diety, Tag.find_all_by_kind("Deity").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("Deity")) %>.
Yeehaw! I want to be a <%= select(:tag, :person, Tag.find_all_by_kind("Person").collect{|t| [ t.name,t.id]}, :selected => @tournament.tag_by_kind("Person")) %>.
<br/><input type="submit">
</form>
</div>
<br/>


<%# @tournament.tags.each do |tag| %>
  <%#= tag.name %> <%#= link_to 'Remove', remove_tournament_tag_path(@tournament,tag), :method => :post, :remote => "true" %><br/>
<%# end %>

<%# @tags.each do |tag| %>
  <%#= link_to tag.name, add_tournament_tag_path(@tournament,tag), :method => :post, :remote => "true" %><br/>
<%# end %>