config/routes.rb
Bracket::Application.routes.draw do
  devise_for :users

  get "pages/home"
  get "pages/info"
  get "pages/contact"
  get "pages/table"

  resources :tags
  resources :teams
  resources :users do
    resources :tournaments
  end

  match '/' => 'pages#ncaa', :as => 'user_root'

  match 'teams/:id/add/:tag_id' => 'teams#add_tag', :as => :add_tag, :via => :post
  match 'users/:id/add/:tag_id' => 'users#add_tag', :as => :add_user_tag, :via => :post
  match 'tournaments/:id/add/:tag_id' => 'tournaments#add_tag', :as => :add_tournament_tag, :via => :post
  match 'teams/:id/remove/:tag_id' => 'teams#remove_tag', :as => :remove_tag, :via => :post
  match 'users/:id/remove/:tag_id' => 'users#remove_tag', :as => :remove_user_tag, :via => :post
  match 'tournaments/:id/remove/:tag_id' => 'tournaments#remove_tag', :as => :remove_tournament_tag, :via => :post
  match 'tournaments/:id/questions' => 'tournaments#questions', :as => :tournament_questions, :via => :get
  match 'tournaments/:id/questions' => 'tournaments#update_questions', :as => :tournament_questions, :via => :post
  match 'tournaments/:id/redo' => 'tournaments#redo', :as => :tournament_redo, :via => :post

  root :to => "pages#ncaa"

end

app/models/tag.rb
class Tag < ActiveRecord::Base

has_and_belongs_to_many :teams
has_and_belongs_to_many :users
has_and_belongs_to_many :tournaments

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
      format.js  { render :layout => false }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(tags_path(), :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plural_name %><br />
    <%= f.text_field :plural_name %>
  </div>
  <div class="field">
    <%= f.label :kind %><br />
    <%= f.text_field :kind %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<%= link_to 'New Tag', new_tag_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Plural</th>
    <th>Kind</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= tag.plural_name %></td>
    <td><%= tag.kind %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>

<p>
  <b>Kind:</b>
  <%= @tag.kind %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>