config/routes.rb
Bracket::Application.routes.draw do
  devise_for :users

  get "pages/home"
  get "pages/info"
  get "pages/contact"
  get "pages/table"

  resources :tags
  resources :teams
  resources :users do
    resources :tournaments
  end

  match '/' => 'pages#ncaa', :as => 'user_root'

  match 'teams/:id/add/:tag_id' => 'teams#add_tag', :as => :add_tag, :via => :post
  match 'users/:id/add/:tag_id' => 'users#add_tag', :as => :add_user_tag, :via => :post
  match 'tournaments/:id/add/:tag_id' => 'tournaments#add_tag', :as => :add_tournament_tag, :via => :post
  match 'teams/:id/remove/:tag_id' => 'teams#remove_tag', :as => :remove_tag, :via => :post
  match 'users/:id/remove/:tag_id' => 'users#remove_tag', :as => :remove_user_tag, :via => :post
  match 'tournaments/:id/remove/:tag_id' => 'tournaments#remove_tag', :as => :remove_tournament_tag, :via => :post
  match 'tournaments/:id/questions' => 'tournaments#questions', :as => :tournament_questions, :via => :get
  match 'tournaments/:id/questions' => 'tournaments#update_questions', :as => :tournament_questions, :via => :post
  match 'tournaments/:id/redo' => 'tournaments#redo', :as => :tournament_redo, :via => :post

  root :to => "pages#ncaa"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bracket</title>
  <%= stylesheet_link_tag 'scaffold','bracket' %>
  <script src="https://www.google.com/jsapi?key=ABQIAAAAIV5Obu0VdsAWmIPelbWXbRQ3xZ8itk8Qm3mo0bDOTeoyembSNRTBtfAlB6PeVGGwEZhDMnMjdVQeuQ" type="text/javascript"></script>
  <%#<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/dark-hive/jquery-ui.css" type="text/css" rel="Stylesheet" />%>
  <%#<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/excite-bike/jquery-ui.css" type="text/css" rel="Stylesheet" />%>
  <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/smoothness/jquery-ui.css" type="text/css" rel="Stylesheet" />
  <script language="Javascript" type="text/javascript">
    google.load("jquery", "1.4.4");
    google.load("jqueryui", "1.8.9");
    google.setOnLoadCallback;
  </script>
  <%= javascript_include_tag 'application','rails.js','pages' %>
  <%= csrf_meta_tag %>
</head>
<body>

<div class="header">

<ul>
  <li><%= link_to "Home", pages_home_path, :class => "ajax" %></li>
  <li><%#= link_to "Public Brackets", "", :class => "ajax" %></li>
  <% if user_signed_in? %>
    <li><%= link_to "My Info", edit_user_path(current_user), :class => "ajax" %></li>
    <li><%= link_to "My Brackets", user_tournaments_path(current_user), :class => "ajax" %></li>
  <% end %>
  <%# NEED USER ADMIN HERE %>

  <% if current_user %>
    <% if current_user.email == "dustinsmith1024@hotmail.com" %>
      <li><%= link_to "Tags", tags_path, :class => "ajax-not" %></li>
      <li><%= link_to "Teams", teams_path, :class => "ajax-not" %></li>
    <% end %>
  <% end %>

  <% if user_signed_in? %>
    <li class="account"><%= link_to "Sign Out", destroy_user_session_path() %></li>
  <% else %>
    <li class="account"><%= link_to "Sign In", new_user_session_path(), :class => "ajax" %></li>
    <li class="account"><%= link_to "Sign Up", new_user_registration_path(), :class => "ajax" %></li>
  <% end %>

  <li class="account"><p class="notice"><%= notice %></p></li>
  <li class="account"><p class="alert"><%= alert %></p></li>

</ul>

<br />

</div>
<div class="main-content">
<div id="popup" class="popup">
<div class="popup-header"><div class="title">TITLE</div>
<a href="#" class="popup-close">Close</a>
</div>
  <p class="body">
  Hi
  </p>
</div>
<%= yield %>
</div>
</body>
</html>